%%\documentclass[11pt,a4paper]{report}
%%\usepackage[polish]{babel}
%%\usepackage[utf8]{inputenc}
%%\usepackage[margin=3.5cm]{geometry}
%%\usepackage{graphicx}
%%\usepackage[T1]{fontenc}

%% ########################################################
%%\begin{document}
\thispagestyle{empty}
\begin{center}
\includegraphics[width=\textwidth]{logo_AGH.jpg}\\
{\bf{\sf WYDZIAŁ FIZYKI I INFORMATYKI STOSOWANEJ}}\\[5mm]
%% ======================================================
{\bf{\sf{KATEDRA INFORMATYKI STOSOWANEJ I FIZYKI KOMPUTEROWEJ}}}\\[14mm]
%% KATEDRA FIZYKI CIAŁA STAŁEGO
%% KATEDRA FIZYKI MATERII Skondensowanej
%% KATEDRA FIZYKI MEDYCZNEJ I BIOFIZYKI
%% KATEDRA INFORMATYKI STOSOWANEJ I FIZYKI KOMPUTEROWEJ
%% KATEDRA ODDZIAŁYWAŃ I DETEKCJI CZĄSTEK
%% KATEDRA ZASTOSOWAŃ FIZYKI JĄDROWEJ
%% ======================================================
{\sf{\huge \sphinxDocumentTitle}}\\[12mm] 
%% Projekt dyplomowy = inżynierska
%% Praca dyplomowa = magisterska
%% ======================================================
{\sf{\Large \sphinxDocumentSubtitle\\[2mm] %% Niepotrzebne usunąć
\sphinxDocumentSubtitleBis %%\\[2mm] %% Jeżeli praca została napisana w języku innym niż język polski
%% Tytuł pracy w języku angielskim %% Jeżeli praca została napisana w języku innym niż język angielski
%% ======================================================
%% W przypadku pracy napisanej
%% - po polsku: dwa tytuły,
%% - po angielsku: dwa tytuły,
%% - po hiszpańsku/niemiecku/rosyjsku/etc: trzy tytuły.
%% ======================================================
}}\\[40mm]
\end{center}
{\sf
\begin{tabular}{ll}
Autor: & \sphinxDocumentAuthor\\
\ifdefined\sphinxDocumentProfile
Kierunek studiów: &	\sphinxDocumentProfile\\
\fi
%% Fizyka Techniczna
%% Fizyka Medyczna
%% Informatyka Stosowana 
%% Mikro- i Nanotechnologie w biofizyce
%% Nanoinżynieria Materiałów
%% Computer Physics
\ifdefined\sphinxDocumentProtector
Opiekun pracy: & \sphinxDocumentProtector\\
\fi
\end{tabular}
}\\[10mm]
\begin{center}
{\sf \sphinxDocumentTownAndYear}
\end{center}

%% ########################################################
\newpage
%% ########################################################
%%\end{document}

